version: "3"

services:
  SERVICE_NAME:
    image: oletepela/backend:latest
    container_name: theaterke-api-staging
    ports:
      - "5000:5000"
    restart: on-failure
    env_file: .env
    volumes:
      - theaterke-backend-logs:/app/logs
volumes:
  theaterke-backend-logs: {}
