version: "3"

services:
  SERVICE_NAME:
    image: oletepela/theatreke-prod:latest
    container_name: theaterke-api
    ports:
      - "5100:5100"
    restart: on-failure
    env_file: .env
    volumes:
      - theaterke-backend-logs:/app/logs
volumes:
  theaterke-backend-logs: {}
