version: "3"

services:
  SERVICE_NAME:
    image: oletepela/backend:latest
    container_name: theaterke-api
    ports:
      - "5000:5000"
    restart: on-failure
    env_file: .env
    volumes:
      - theaterke-backend-logs:/app/logs
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file: .env
    ports:
      - 27017:27017
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  theaterke-backend-logs: {}
