name: Build and Test
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Read env file
        run: echo '${{ secrets.ENV_FILE }}' > .env
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set repository name
        id: repo_name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: oletepela/${{ steps.repo_name.outputs.REPO_NAME }}
      - name: Copy compose file
        id: copy_compose
        run: |
          {
            echo 'file<<EOF'
            sed 's/\${/\\\${/g' docker-compose.yaml
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p ${{ steps.repo_name.outputs.REPO_NAME }}
            cd ${{ steps.repo_name.outputs.REPO_NAME }}
            echo '${{ secrets.ENV_FILE }}' > .env
            cat << EOF > docker-compose.yaml
            ${{ steps.copy_compose.outputs.file }}
            EOF
            docker compose pull
            docker compose --env-file .env up -d --remove-orphans
            docker image prune -f
