name: Scaleway Ubuntu(22.04)
on:
  push:
    branches: [develop]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repository name
        id: repo_name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
      - name: Login to Docker registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin hub.docker.com
      - name: Build Docker image
        run: docker build oletepela/${{ steps.repo_name.outputs.REPO_NAME }} .

      - name: Push Docker image to registry
        run: docker push oletepela/${{ steps.repo_name.outputs.REPO_NAME }}
      - name: Copy compose file
        id: copy_compose
        run: |
          {
            echo 'file<<EOF'
            sed 's/\${/\\\${/g' docker-compose.yml
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: run docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p ${{ steps.repo_name.outputs.REPO_NAME }}
            cd ${{ steps.repo_name.outputs.REPO_NAME }}
            echo '${{ secrets.ENV_FILE }}' > .env
            cat << EOF > docker-compose.yml
            ${{ steps.copy_compose.outputs.file }}
            EOF
            docker compose pull
            docker compose --env-file .env up -d --remove-orphans
            docker image prune -f
